# Generated by Django 3.1.3 on 2020-11-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201120_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='photo',
            field=models.ImageField(default=1, upload_to='listings'),
            preserve_default=False,
        ),
    ]
