# Generated by Django 3.1.3 on 2020-11-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20201124_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, choices=[('WPN', 'Weapons'), ('GRN', 'Greens'), ('TEC', 'Technology'), ('OTR', 'Other'), ('AFT', 'Artifact')], max_length=3),
        ),
    ]
